### ISSUE TITLE
Small syntax error

### ISSUE THREAD

**Issue by ethicalhack3r** [doyensec/graph-ql#1]
Thanks for the script,  I noticed a small syntax error in the `key` hash.

Current:

```
headers = {
			"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"
			"Authorization: "+key
		}
```

Should be:

```
headers = {
			"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0",
			"Authorization": key
		}
```

https://github.com/doyensec/graph-ql/blob/455c828a61f04ec85ae0e98aa26b933f795a433f/Introspection/GraphQL_Introspection.py#L59

**Comment by VoidSec** [comment]
Thanks, issue is now fixed :)
