### ISSUE TITLE
GET method?

### ISSUE THREAD

**Issue by zer0dots** [doyensec/graph-ql#11]
How can I send GET request with this script?

```
python GraphQL_Introspection.py -t https://graphql.org/swapi-graphql/
[!] Trying the old introspection query
[!] Query failed! Code 405
```

**Comment by VoidSec** [comment]
Unfortunately there is no option to do that in the script at the moment. I would suggest to send the above query as GET **query** parameter, save the result in a file.json and parse it with the appropriate option (-f).
`query IntrospectionQuery{__schema{queryType{name}mutationType{name}subscriptionType{name}types{...FullType}directives{name description locations args{...InputValue}}}}fragment FullType on __Type{kind name description fields(includeDeprecated:true){name description args{...InputValue}type{...TypeRef}isDeprecated deprecationReason}inputFields{...InputValue}interfaces{...TypeRef}enumValues(includeDeprecated:true){name description isDeprecated deprecationReason}possibleTypes{...TypeRef}}fragment InputValue on __InputValue{name description type{...TypeRef}defaultValue}fragment TypeRef on __Type{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name}}}}}}}}`
