### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by unkn0wn-us3r** [doyensec/graph-ql#14]
Hi,
Really great work @VoidSec! I really appreciate the project and the efforts you have put into it. We would like to use the project for a commercial training online/classroom. So, I just wanted to clarify, if we acknowledge the source, would that be sufficient and covered under the terms of use?

**Comment by VoidSec** [comment]
hI @unkn0wn-us3r thank you very much, I'm glad that you'd found that useful.
@ikkisoft will be able to elaborate a bit further on your request.

**Comment by unkn0wn-us3r** [comment]
Hi thanks for a quick reply @VoidSec. Waiting for @ikkisoft's reply on the same.

Thanks.

**Comment by ikkisoft** [comment]
I've made a PR to push the license file. This is released as "Apache License 2.0" so, yes - you can use it for commercial use as long as you respect the additional requirements (e.g. credits, etc.)

**Comment by ikkisoft** [comment]
Closing this issue
