### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by wisahmed** [doyensec/graph-ql#5]
I keep getting this error when I use the -t flag. Please help!

I have tried it in Kali as well as Mac.

> Traceback (most recent call last):
>   File "GraphQL_Introspection.py", line 395, in <module>
>     main()
>   File "GraphQL_Introspection.py", line 214, in main
>     if result['data']['__schema']['subscriptionType']['name'] is not None:
> TypeError: 'NoneType' object has no attribute '__getitem__'
>

**Comment by VoidSec** [comment]
Could you please provide the exact command that you are using?
If it is a sensible URL: PM me.

eg.```
$python GraphQL_Introspection.py -t http://192.168.1.82/examples/04-bank/graphql 
```

**Comment by VoidSec** [comment]
Fixed in dev
#219-231
