### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode unicode character

### ISSUE THREAD

**Issue by w3kwang** [doyensec/graph-ql#6]
Traceback (most recent call last):
  File "GraphQL_Introspection.py", line 831, in <module>
    main()
  File "GraphQL_Introspection.py", line 616, in main
    rt[i]['fields'][j]['args'][x]['description']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 110: ordinal not in range(128)

**Comment by VoidSec** [comment]
Fixed in https://github.com/doyensec/graph-ql/commit/858e080a89a59c59e34e8a820eb4ea46827be636

**Comment by w3kwang** [comment]
Thanks for the fix. will verify & try out in two weeks on another project.

**Comment by VoidSec** [comment]
Yes please, let me know. :)
